# Generated by Django 5.1.2 on 2024-10-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=224)),
                ("phonenumber", models.CharField(max_length=12)),
                ("address", models.CharField(max_length=225)),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("occupation", models.CharField(max_length=128)),
                ("state", models.CharField(max_length=64)),
                (
                    "evidence",
                    models.FileField(blank=True, null=True, upload_to="evidences"),
                ),
                ("case_type", models.CharField(max_length=128)),
                ("description", models.TextField()),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Active"), (2, "Pending Review"), (3, "Resolved")]
                    ),
                ),
                ("code", models.IntegerField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
