# Generated by Django 5.1.2 on 2024-11-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0002_alter_case_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="case",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="case",
            name="case_received_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="initial_review_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="investigation_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="resolution_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="case",
            name="address",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="case",
            name="case_type",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="case",
            name="code",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="case",
            name="evidence",
            field=models.FileField(blank=True, null=True, upload_to="evidence/"),
        ),
        migrations.AlterField(
            model_name="case",
            name="fullname",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="case",
            name="occupation",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="case",
            name="phonenumber",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="case",
            name="sex",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="case",
            name="state",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="case",
            name="status",
            field=models.CharField(
                choices=[
                    ("Received", "Case Received"),
                    ("Review", "Initial Review Completed"),
                    ("Investigation", "Investigation In Progress"),
                    ("Resolution", "Resolution"),
                ],
                default="Received",
                max_length=50,
            ),
        ),
    ]
